export const SAVE_SEARCH_OPTIONS = 'SAVE_SEARCH_OPTIONS';
export const RESTORE_SEARCH_OPTIONS = 'RESTORE_SEARCH_OPTIONS';

export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export const FETCH_FAVOURITE_GIF_LIST = 'FETCH_FAVOURITE_GIF_LIST';
export const SAVE_GIF_TO_FAVOURITES = 'SAVE_GIF_TO_FAVOURITES';
export const REMOVE_GIF_FROM_FAVOURITES = 'REMOVE_GIF_FROM_FAVOURITES';
export const FETCH_FAVOURITE_GIF_LIST_COUNT = 'FETCH_FAVOURITE_GIF_LIST_COUNT';
